# Generated by Django 4.0.6 on 2022-07-15 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviroment', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=100)),
                ('benefits', models.CharField(max_length=100)),
                ('culture', models.CharField(max_length=100)),
                ('programs', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('weather_type', models.CharField(max_length=30)),
                ('major_type', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
